version: '3'

services:
  app:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
      args:
        - UID=$UID
        - GID=$GID
    env_file: docker/app/.env
    init: true
    volumes:
      - .:/home/vscode/workspace

  db:
    build: docker/db
    env_file: docker/db/.env
