[package]
name = "controllable-pass"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
diesel = { version = "2.1.0"}
diesel-async = { version = "0.3.1", features = ["postgres"] }
